// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVrZo9-nKC4xBffBmjnP2RAzwXqPwV790',
    appId: '1:372100447655:web:6c5bc3ac17bcbc9213ca82',
    messagingSenderId: '372100447655',
    projectId: 'civicvote-ceb61',
    authDomain: 'civicvote-ceb61.firebaseapp.com',
    storageBucket: 'civicvote-ceb61.firebasestorage.app',
    measurementId: 'G-MFRKJRHX02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZageqIUbgRQdtpo7gk_5Eo-g1Jkr5hgk',
    appId: '1:372100447655:android:38ce674a3c080f8c13ca82',
    messagingSenderId: '372100447655',
    projectId: 'civicvote-ceb61',
    storageBucket: 'civicvote-ceb61.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVrZo9-nKC4xBffBmjnP2RAzwXqPwV790',
    appId: '1:372100447655:web:9aaa0d206ce62e6813ca82',
    messagingSenderId: '372100447655',
    projectId: 'civicvote-ceb61',
    authDomain: 'civicvote-ceb61.firebaseapp.com',
    storageBucket: 'civicvote-ceb61.firebasestorage.app',
    measurementId: 'G-2YFFSN90TH',
  );
}
